### ISSUE TITLE
Live queries

### ISSUE THREAD

**Issue by Odonno** [surrealdb/surrealdb.net#11]
* Create a method named `LiveQuery` that should create a new Live Query that returns an `IAsyncEnumerable<T>`
  * Method override using a `Guid` (id of the live query)
  * Method override using the table name and `diff` boolean value (to handle JSON Patch vs. full object) 
* Create a method named `Kill` that should kill a Live Query
* Handle the WS implementation
* Throw `NotSupportedException` for the HTTP implementation
* Add tests
  * Add tests on `IAsyncEnumerable` returns
  * Add tests on Rx.NET `Observable`, using `IAsyncEnumerable.ToObservable()` extension method (Subscribe, Hot vs. Cold, etc...)
* Update documentation
  * Readme file
  * Official documentation website

**Comment by Odonno** [comment]
Will let @S-E-F work on this issue.

**Comment by S-E-F** [comment]
We will have to do some design work around the api's to come to a decision on how users get to filter out certain event types, and whether `IAsyncEnumerable` is the only option or if we let users define callbacks for a more event experience.

Event types ive seen from live queries are
- updated
- created
- deleted

I can see how it would be annoying to have to go through the boilerplate of only subscribing to one of these manually.

**Comment by Odonno** [comment]
I forgot the testing part. I can work on the Rx.NET if you want once you implemented the "core" solution.

Yes, callbacks and event types filtering (via enum?) can be a nice addition. Feel free to add as many overrides as you want.

**Comment by S-E-F** [comment]
I've tried porting my Live Queries work to here but the difference in underlying `ws` implementation is too different making it essentially a full re-write.

Coming back to this later unless someone else wants to pick it up.

**Comment by Odonno** [comment]
I suppose there is some plumbing to do in the first place. 

We should take inspiration of the `SendRequest` method to create a new method that will work with live queries:

* Should return an `IAsyncEnumerable`, with a `yield return` inside a loop
* Should register a new `TaskCompletionSource` for the same id on each loop iteration
* Should use a `SemaphoreSlim` in the `Subscribe` to ensure no entry is ignored when recreating a new `TaskCompletionSource`
