### ISSUE TITLE
Feature: Implement ReadOnlyRecordIdJsonConverter Read

### ISSUE THREAD

**Issue by Isaac-Guillen** [surrealdb/surrealdb.net#133]
### Is your feature request related to a problem?

I have a blazor app that receives models from the backend, but now I get an error saying ReadOnlyRecordIdJsonConverter.Read is not implemented, I don't know what to do without having a great impact in my project

### Describe the solution

I think this will be resolved once the read method is implemented

### Alternative methods

I don't know if there is a way to override the method or I have to do anything else

### SurrealDB version

2

### Package version(s)

El proyecto "Demo.Server" tiene las referencias de paquete siguientes
   [net8.0]:
   Paquete de nivel superior                                 Solicitado   Resuelto
   > Microsoft.AspNetCore.Authentication.JwtBearer           8.0.10       8.0.10
   > Microsoft.AspNetCore.Components.WebAssembly.Server      8.0.10       8.0.10
   > Serilog.AspNetCore                                      8.0.3        8.0.3
   > Serilog.Sinks.File                                      6.0.0        6.0.0
   > Swashbuckle.AspNetCore                                  6.8.1        6.8.1
   > System.IdentityModel.Tokens.Jwt                         8.1.2        8.1.2

El proyecto "Demo.Shared" tiene las referencias de paquete siguientes
   [net8.0]:
   Paquete de nivel superior                 Solicitado   Resuelto
   > Microsoft.AspNetCore.Authorization      8.0.10       8.0.10
   > QuestPDF                                2024.10.1    2024.10.1
   > SkiaSharp.NativeAssets.Linux            2.88.8       2.88.8
   > SurrealDb.Net                           0.6.0        0.6.0

El proyecto "Demo.Client" tiene las referencias de paquete siguientes
   [net8.0]:
   Paquete de nivel superior                                       Solicitado   Resuelto
   > Blazored.SessionStorage                                       2.4.0        2.4.0
   > Microsoft.AspNetCore.Components.Authorization                 8.0.10       8.0.10
   > Microsoft.AspNetCore.Components.WebAssembly                   8.0.10       8.0.10
   > Microsoft.AspNetCore.Components.WebAssembly.DevServer         8.0.10       8.0.10
   > Microsoft.NET.ILLink.Tasks                              (A)   [8.0.10, )   8.0.10
   > Microsoft.NET.Sdk.WebAssembly.Pack                      (A)   [8.0.10, )   8.0.10
   > Radzen.Blazor                                                 5.2.12       5.2.12

### Contact Details

isaac.guillen@proton.me

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Isaac-Guillen** [comment]
Thank you for the response and solutions proposed, I think that in long term would be better to implement DTO Models and mappers, but in the short term, the override solution has any downside?

Thanks!

**Comment by Odonno** [comment]
> Thank you for the response and solutions proposed, I think that in long term would be better to implement DTO Models and mappers, but in the short term, the override solution has any downside?

I do not know if there is any.

**Comment by Isaac-Guillen** [comment]
Thanks a lot for your help!
