### ISSUE TITLE
Discussion: Supported Releases

### ISSUE THREAD

**Issue by S-E-F** [surrealdb/surrealdb.net#14]
The current support windows (5 year LTS) extend support for .NET versions beyond Microsoft's support windows (3 year LTS). The commitment is admirable but ultimately more work than we need to take on imo. If a runtime version is no longer officially supported by Microsoft, why would we maintain support for that version.

Additionally, I would like to see a cautious plan to provide STS support as well, in their appropriate support windows (18 months). Not only would STS users reap benefits, but we would be more gradually moving to the next LTS as well.

**Comment by Odonno** [comment]
Thank you for putting this discussion here.

I can see your point of view. At the moment, the only pain points are coming from .NET Standard compatibility. Supporting .NET 5 through .NET 7 is currently almost painless, I am pretty sure it will still be the case for .NET 8. If that changes, I will be the first to come here and change my view on this. :)

.NET Standard is and will be a huge topic in the future. Supporting it with the first releases will be good for various reasons but then, we will definitively make the hard decision at some point in the future. 

And, yes, I did miss STS. This could be a nice addition to the readme. Given then time frame of when we start to support it and for how long. Same for LTS I suppose.

**Comment by Odonno** [comment]
Hello @S-E-F 

I made some changes on #20 that should reflect engagement for the .NET versions support on LTS/STS. I've also added .NET 7 as a target framework.

Let me know what you think.

**Comment by S-E-F** [comment]
Good to see clarification on this, I've added some comments on the PR

**Comment by Odonno** [comment]
PR #20 merged. I think we have a good explanation on the readme file now. If you still have any suggestion on this @S-E-F, I will be happy to take the feedback.
