### ISSUE TITLE
Feature: Allow JsonSerializerOptions configuration for deserializing responses

### ISSUE THREAD

**Issue by AskoldMakaruk** [surrealdb/surrealdb.net#34]
Expose JsonSerializerOptions configuration, so finetuning serialization is possible.

**Comment by Odonno** [comment]
Hi @AskoldMakaruk 

Yes, I can totally see that. Just out of curiosity, what kind of JsonSerializer do you have in mind that is not handled in the current version of the library?

**Comment by AskoldMakaruk** [comment]
I have some code that is already uses camelcase in field naming when creating records and I have no way of changing your config, so it uses another naming style
