### ISSUE TITLE
JsonNamingPolicy Question

### ISSUE THREAD

**Issue by ronnieoverby** [surrealdb/surrealdb.net#80]
I'm curious what the reason is for choosing lowercase snake JsonNamingPolicy?

**Comment by Odonno** [comment]
Hello Ronnie,

The snake case policy follows the recommended practices for SurrealDB. Tables and fields uses snake case naming policy.

**Comment by ronnieoverby** [comment]
I see. It caused me confusion because of the opposing convention to not
name c# properties that way. When I tried querying, my predicates weren’t
satisfied.

**Comment by ronnieoverby** [comment]
@Odonno Where is that recommendation made and why? I don't see that practice in all of their examples. See this one for instance having fields like `lastName`:

https://docs.surrealdb.com/docs/1.0.x/surrealql/statements/define/table/#schemaless-tables
