### ISSUE TITLE
How to get the id back from the Create method?

### ISSUE THREAD

**Issue by pires22** [surrealdb/surrealdb.net#86]
I tried to create a record in the database using the Create method. If I dont put an Id property in the object it works fine, but then I don't get the id back from the Create method. If I put the id property, I receive an error because I can't send a null id or an empty string, but I would like SurrealDB to generate the id for me.

Any suggestions?

**Comment by Odonno** [comment]
Hello Henrique,

I am curious about this. If you don't provide an id, SurrealDB will create a random one. I played with the Console example project and it works as expected. 

![image](https://github.com/surrealdb/surrealdb.net/assets/6053067/c6209369-1970-47b9-8f0e-6a86fdcfe244)


Are you able to provide more details/code to see where the problem can be?

**Comment by pires22** [comment]
I think I get it now. In the console example the Person object extends Record from SurrealDB Models, and I realize now that Record has an Id property.

So if I extend the Record class on my objects it should work.

This issue is solved but I have another problem now that is related to this solution.

The Id property of my objects have customized getter and setter because I like to remove the "table:" from the Id string as follows:
```
public class ApplicationDto
{
    private string _id;
    public string Id
    {
        get => _id;
        set { _id = value[(value.IndexOf(':') + 1)..]; }
    }

    [JsonPropertyName("name")]
    public required string Name { get; set; }

    [JsonPropertyName("equipments")]
    public IEnumerable<EquipmentDto?> Equipments { get; set; }

    [JsonPropertyName("created_at")]
    public DateTime CreatedAt { get; set; }
}
```

Is there any way I can use the Id property from the Record class and customize it with a getter and a setter?

**Comment by Odonno** [comment]
Good question. 

Simplest way to solve that would be to create a mapper between the Api object and the Dto object.

If you really want to stay with a single class, i suppose it could be possible to override the `id` property by setting a custom Converter. Deserializing won't be a big problem but the hard part would be to detect what table name should used when serializing. I do not have the solution yet.

**Comment by pires22** [comment]
I will try some stuff and see what I can find.

**Comment by pires22** [comment]
@Odonno 

Here is the solution I did following your suggestion:

```
public class ApplicationDto : Record
{
    /// <summary>
    /// The id of the record
    /// </summary>
    [JsonConverter(typeof(ThingConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] // 💡 ignore null value to prevent failure on Create operation
    public new Thing? Id { get; set; }

    [JsonPropertyName("name")]
    public required string Name { get; set; }

    [JsonPropertyName("equipments")]
    public IEnumerable<EquipmentDto?> Equipments { get; set; }

    [JsonPropertyName("created_at")]
    public DateTime CreatedAt { get; set; }
}

public sealed class ThingConverter : JsonConverter<Thing>
{
    public override Thing? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return GetValueFromString(reader.GetString());
    }

    private static Thing? GetValueFromString(string? value)
    {
        if (value is null)
            return default;
        return new Thing(value);
    }

    public override void Write(Utf8JsonWriter writer, Thing value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.Id.ToString());
    }
}
```
Just writing value.Id.ToString() solves the problem. 

You talked about serializing with the table name but I don't see where this could be a problem, where does Thing get serialized?

**Comment by Odonno** [comment]
When updating a record for example.

**Comment by pires22** [comment]
I just tried it and yeah it doesn't work. I think the better alternative would be to map the database object to another object with costumized id so updating the database object would not be a problem.

Since the main issue is solved, I will close it. Thank you @Odonno for your support!
