### ISSUE TITLE
How to create objects that have other objects as properties?

### ISSUE THREAD

**Issue by pires22** [surrealdb/surrealdb.net#87]
Considering the following object:

```
public class ComponentDto : Record
{
    [JsonConverter(typeof(CustomThingConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public new Thing? Id { get; set; }

    [JsonPropertyName("parent")]
    public DeviceDto? Parent { get; set; }

    [JsonPropertyName("sensor")]
    public SensorDto? Sensor { get; set; }

    [JsonPropertyName("status")]
    public string Status { get; set; }
}
```

Parent and Sensor are other objects in my application.

Considering that I wanna create a new ComponentDto and insert in the database, the following situation happens:

I instantiate the ComponentDto and I need to assign the Parent and the Sensor, but since SurrealDB relates things with the record type "table:id" and you do a FETCH to fetch the relations, I would need to assign a string "devices:id" to Parent and "sensors:id" to Sensor properties, but I can't do that since their types are not string.

My approach now will be to create the record with Parent and Sensor properties null and update the created component record with a `surrealDbClient.Query()` method where I can assign them to string and there is no type conflicts.

Is there any other approach that would be more suitable?

**Comment by Odonno** [comment]
Why not create your Dto this way?

```csharp
public class ComponentDto : Record
{
    [JsonConverter(typeof(CustomThingConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public new Thing? Id { get; set; }

    [JsonPropertyName("device")]
    public Thing? Device { get; set; }

    [JsonPropertyName("sensor")]
    public Thing? Sensor { get; set; }

    [JsonPropertyName("status")]
    public string Status { get; set; }
}
```

I am not sure if they are nullable or not. When saving a component, it will set the according record fields in the database. Consuming data would be very different. There is a plan for a Query builder but until then, I suggest you to use the `Query` for this.

And same as the previous issue, if you need only use the id from the Thing in your API layer, you are gonna need a mapper between the Dto and the Api layer.

Does it suit your needs?

**Comment by pires22** [comment]
Lets see if I  understand:

If I use the object you suggested, I can insert Parent and Sensor as Things. When I do a `Query()` in the database, I pass another object to the method for the output and this object has the Dto type from Parent and Sensor. Is that right?

In code:

```c#
ObjectYouSuggested object1 = new();
surrealDbClient.Create(object1);
...
surrealDbClient.Query<Object2WithTheDtoTypes>($"select ... from ... fetch parent, sensor");
```

**Comment by Odonno** [comment]
In most cases, yes. It is the pattern to follow. That would allow you in some way to dissociate the Read model (querying data the way you want) and the Write model (updating records).

There is also a plan for an ORM to simplify these actions but for now, this is what I would recommend.

**Comment by pires22** [comment]
Ok, thanks again for your help!
